spring:
    jooq:
        sql-dialect: POSTGRES
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: ${POSTGRES_ROOT_USER:admin}
        password: ${POSTGRES_ROOT_PASSWORD:supersecurepassword}
    flyway:
        enabled: true
        locations: classpath:db/migration

server:
    error:
        include-message: always
        include-binding-errors: always
